formatter: "markdown table" # this is required

version: "0.18"

header-from: main.tf

footer-from: ""

recursive:
  enabled: false
  path: ""

sections:
  hide: []
  show: []

content: |-
  # Vault-backed Azure Dynamic Credentials with persistent Service Principals

  This module deploys resources to support VCS-driven Azure Infrastructure Automation using dynamic credentials. Dynamic credentials (client secret) for an existing Service Principal are managed and delivered by HashiCorp Vault.

  ## GitHub

  | Resource Type | Resource | Description |
  |---------------|----------|-------------|
  | GitHub Repo | project-\<project_name> | GitHub private repository |
  | GitHub Repo Branch | project-\<project_name>/main | VCS branch for tracking code intended for the Production environment |
  | GitHub Repo Branch | project-\<project_name>/stage | VCS branch for tracking code intended for the Staging environment |
  | GitHub Repo Branch | project-\<project_name>/dev | VCS branch for tracking code intended for the Devlopment environment |

  ## HCP Terraform

  | Resource Type | Resource | Description |
  |---------------|----------|-------------|
  | Terrform Workspace | project-\<project_name>-prod | Terraform workspace tracking infrastructure automation for the Production environment. Configured with VCS-connectivity to the main branch  |
  | Terrform Workspace | project-\<project_name>-stage | Terraform workspace tracking infrastructure automation for the Staging environment. Configured with VCS-connectivity to the stage branch  |
  | Terrform Workspace | project-\<project_name>-dev | Terraform workspace tracking infrastructure automation for the Development environment. Configured with VCS-connectivity to the dev branch  |

  ## Azure

  | Resource Type | Resource | Description |
  |---------------|----------|-------------|
  | Azure Service Prinicipal | project-\<project_name>-prod | Azure Service Prinicipal for access to the Azure Production environment |
  | Azure Service Prinicipal | project-\<project_name>-stage | Azure Service Prinicipal for access to the Azure Staging environment |
  | Azure Service Prinicipal | project-\<project_name>-dev | Azure Service Prinicipal for access to the Azure Development environment |

  ## Vault

  | Resource Type | Resource | Description |
  |---------------|----------|-------------|
  | JWT auth role | project-\<project_name>-prod | Authorization role for Terrform to authenticate and acccess Production dynamic credentials |
  | JWT auth role | project-\<project_name>-stage | Authorization role for Terrform to authenticate and acccess Staging dynamic credentials |
  | JWT auth role | project-\<project_name>-dev| Authorization role for Terrform to authenticate and acccess Development dynamic credentials |
  | Policy | project-\<project_name>-prod | Vault policy to authorize JWT auth method to request credentials from the Azure secrets engine for Production |
  | Policy | project-\<project_name>-stage | Vault policy to authorize JWT auth method to request credentials from the Azure secrets engine for Staging |
  | Policy | project-\<project_name>-dev | Vault policy to authorize JWT auth method to request credentials from the Azure secrets engine for Development |
  | Azure secrets role | project-\<project_name>-prod | Azure secrets engine role for Terrform to request Production dynamic credentials |
  | Azure secrets role | project-\<project_name>-stage | Azure secrets engine role for Terrform to request Staging dynamic credentials |
  | Azure secrets role | project-\<project_name>-dev | Azure secrets engine role for Terrform to request Development dynamic credentials |

  {{ .Requirements }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace 
  template: |-
      <!-- BEGIN_AUTOMATED_TF_DOCS_BLOCK -->
      {{ .Content }}
      <!-- END_AUTOMATED_TF_DOCS_BLOCK -->

output-values:
  enabled: false
  from: outputs.tf

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true